package art.cipher581.commons.gui;


import java.awt.Dimension;
import java.awt.image.BufferedImage;
import javax.swing.JFrame;


public class ImageFrame extends JFrame {

    /**
	 * SVUID
	 */
	private static final long serialVersionUID = 1950369139743852247L;


	public ImageFrame(BufferedImage image) {
        super();

        initComponents();

        Dimension dimension = new Dimension(image.getWidth(), image.getHeight());

        ImagePanel imagePanel = new ImagePanel(image, null);
        imagePanel.setSize(dimension);
        imagePanel.setPreferredSize(dimension);
        imagePanel.setMaximumSize(dimension);
        imagePanel.setMinimumSize(dimension);

        add(imagePanel);

        Dimension frameDimension = new Dimension(image.getWidth() + 10, image.getHeight() + 40);
        setSize(frameDimension);
    }


    public static void showAndWait(BufferedImage image) {
        ImageFrame imageFrame = new ImageFrame(image);
        imageFrame.setVisible(true);

        while (imageFrame.isVisible()) {
            try {
                Thread.sleep(100);
            } catch (InterruptedException ex) {
                // ignore
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
