package art.cipher581.commons.gui;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;

import javax.swing.JPanel;

import art.cipher581.commons.util.img.IImageModifier;
import art.cipher581.commons.util.img.IImageScaler;
import art.cipher581.commons.util.img.ImageUtils;

/**
 * 
 * @author __USER__
 */
public class ImagePanel extends JPanel {

	/**
	 * SVUID
	 */
	private static final long serialVersionUID = 5383096442840828415L;

	private BufferedImage image;

	private IImageScaler imageScaler;

	private IImageModifier imageModifier;

	/** Creates new form ImagePanel */
	public ImagePanel(BufferedImage image, IImageScaler imageScaler) {
		super();

		this.image = image;
		this.imageScaler = imageScaler;

		initComponents();
	}

	public void setImageModifier(IImageModifier imageModifier) {
		this.imageModifier = imageModifier;

		repaint();
	}

	public IImageModifier getImageModifier() {
		return imageModifier;
	}

	@Override
	public void paint(Graphics g) {
		BufferedImage imgPaint = getPaintedImage();

		g.drawImage(imgPaint, 0, 0, imgPaint.getWidth(), imgPaint.getHeight(), Color.WHITE, null);
	}

	public BufferedImage getPaintedImage() {
		BufferedImage imgPaint;

		if (image == null) {
			imgPaint = ImageUtils.createImage(getWidth(), getHeight(), Color.WHITE);
		} else {
			if (imageScaler == null) {
				imgPaint = image;
			} else {
				imgPaint = imageScaler.scale(image, getWidth(), getHeight());
			}
		}

		if (imageModifier != null) {
			imgPaint = imageModifier.modify(imgPaint);
		}

		return imgPaint;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400, Short.MAX_VALUE));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 300, Short.MAX_VALUE));
	}// </editor-fold>
		// GEN-END:initComponents

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	// End of variables declaration

}